/mm:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
  
  manipulator_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - mm/shoulder_pan_joint
      - mm/shoulder_lift_joint
      - mm/elbow_joint
      - mm/wrist_1_joint
      - mm/wrist_2_joint
      - mm/wrist_3_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_a1: {trajectory: 0.01, goal: 0.01}
      joint_a2: {trajectory: 0.01, goal: 0.01}
      joint_a3: {trajectory: 0.01, goal: 0.01}
      joint_a4: {trajectory: 0.01, goal: 0.01}
      joint_a5: {trajectory: 0.01, goal: 0.01}
      joint_a6: {trajectory: 0.01, goal: 0.01}
      joint_a7: {trajectory: 0.01, goal: 0.01}
    stop_trajectory_duration: 0.5
    state_publish_rate:  50
    action_monitor_rate: 20
    gains:
      mm/shoulder_pan_joint: {p: 10.0, i: 1, d: 1.0}
      mm/shoulder_lift_joint: {p: 10.0, i: 1, d: 1.0}
      mm/elbow_joint: {p: 10.0, i: 1, d: 1.0}
      mm/wrist_1_joint: {p: 10.0, i: 1, d: 1.0}
      mm/wrist_2_joint: {p: 10.0, i: 1, d: 1.0}
      mm/wrist_3_joint: {p: 10.0, i: 1, d: 1.0}