/mm:
  manipulator_controller:
    type: effort_controllers/JointGroupVelocityController
    joints:
      - mm/virtual_x
      - mm/virtual_y
      - mm/virtual_z
      - mm/shoulder_pan_joint
      - mm/shoulder_lift_joint
      - mm/elbow_joint
      - mm/wrist_1_joint
      - mm/wrist_2_joint
      - mm/wrist_3_joint

    gains:
      - mm/virtual_x: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/virtual_y: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/virtual_z: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/shoulder_pan_joint: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/shoulder_lift_joint: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/elbow_joint: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/wrist_1_joint: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/wrist_2_joint: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}
      - mm/wrist_3_joint: {p: 10, i: 10, d: 1, i_clamp_min: 0, i_clamp_max: 20}

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50








 
