joint1_controller:
  type: velocity_controllers/JointVelocityController
  joint: shoulder_pan_joint
  pid_gains: { p: 5.0, i: 20.0, d: 1, i_clamp: 100.0}

joint2_controller:
  type: velocity_controllers/JointVelocityController
  joint: shoulder_lift_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint3_controller:
  type: velocity_controllers/JointVelocityController
  joint: elbow_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint4_controller:
  type: velocity_controllers/JointVelocityController
  joint: wrist_1_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint5_controller:
  type: velocity_controllers/JointVelocityController
  joint: wrist_2_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0
joint6_controller:
  type: velocity_controllers/JointVelocityController
  joint: wrist_3_joint
  pid:
    p: 5.0
    i: 20.0
    i_clamp: 100.0

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#gazebo_ros_control:   
#  pid_gains:
#    shoulder_pan_joint:
#      p: 100.0
#      i: 0.01 
#      d: 10.0
#    shoulder_lift_joint:
#      p: 100.0
#      i: 0.01 
#      d: 10.0

#    elbow_joint:
#      p: 100.0
#      i: 0.01 
#      d: 10.0
#    wrist_1_joint:
#      p: 100.0
#      i: 0.01 
#      d: 10.0
#    wrist_2_joint:
#      p: 100.0
#      i: 0.01 
#      d: 10.0
#    wrist_3_joint:
#      p: 100.0
#      i: 0.01 
#      d: 10.0